import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: '#ffffff',
    },
    headerContainer: {
      flex: 1,
      backgroundColor: '#c7f0d9',
      borderBottomLeftRadius: 40,
      borderBottomRightRadius: 40,
      overflow: 'hidden',
    },
    scrollContent: {
      flexGrow: 1,
      paddingBottom: 30,
      alignItems: 'center',
    },
    header: {
      width: '100%',
      alignItems: 'center',
      padding: 10,
    },
    imageBackground: {
      width: 275,
      height: 250,
      alignItems: 'center',
      justifyContent: 'flex-start',
      marginLeft: 'auto',
      marginRight: 'auto',
    },
    greeting: {
      fontFamily: "ClashDisplayBold",
      position: 'absolute',
      top: 70,
      left:10,
      color: '#4E986D',
      textAlign: 'center',
      width:280,
      alignItems:"center",
      justifyContent:"center"
    },
    greetinghelp: {
      fontFamily: "ClashDisplayBold",
        position: 'absolute',
        top:50,
        left:10,
        color: '#1e3a8a',
        textAlign: 'center',
        width:"100%", 
      },
    handsImage: {
      position: 'absolute',
      bottom: 40,
      width: 230,
      height: 100,
    },
    buttonsContainer: {
      maxWidth: 300,
      alignItems: 'center',
      justifyContent:'center',
      flex:1,
      gap: 15,
    },
    containerScan: {
      flex: 1,
      justifyContent: "center",
      borderRadius: 40,
      overflow: "hidden",
      borderWidth: 2,
      borderColor: "white",
    },
    camera: {
      flex: 1,
      overflow: "hidden",
      borderColor: "white",
    },
    overlay: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(255, 255, 255, 0)",
    },
    scanFrameContainer: {
      width: "80%",
      height: 220,
      backgroundColor: "transparent",
      overflow: "hidden",
    },
    scanFrame: {
      flex: 1,
      borderWidth: 2,
      borderColor: "rgba(252, 236, 167, 0.47)",
      borderRadius: 20,
      position: "relative",
    },
    scanCorner: {
      position: "absolute",
      width: 20,
      height: 20,
      borderColor: "#fceca7",
    },
    topLeftCorner: {
      top: -2,
      left: -2,
      borderTopWidth: 3,
      borderLeftWidth: 3,
      borderTopLeftRadius: 20,
    },
    topRightCorner: {
      top: -2,
      right: -2,
      borderTopWidth: 3,
      borderRightWidth: 3,
      borderTopRightRadius: 20,
    },
    bottomLeftCorner: {
      bottom: -2,
      left: -2,
      borderBottomWidth: 3,
      borderLeftWidth: 3,
      borderBottomLeftRadius: 20,
    },
    bottomRightCorner: {
      bottom: -2,
      right: -2,
      borderBottomWidth: 3,
      borderRightWidth: 3,
      borderBottomRightRadius: 20,
    },
    instructionText: {
      color: "#fceca7",
      marginTop: 10,
      fontSize: 14,
      textAlign: "center",
    },
    buttonContainer: {
      position: "absolute",
      bottom: 20,
      width: "100%",
      flexDirection: "row",
      justifyContent: "space-evenly",
    },
    iconButton: {
      backgroundColor: "rgba(255,255,255,0.2)",
      padding: 10,
      borderRadius: 50,
    },
    barcodeContainer: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: "rgba(0,0,0,0.5)",
      padding: 10,
    },
    barcodeText: {
      color: "white",
      textAlign: "center",
    },
  });
  